package com.example.demo.user.dao;

import java.util.List;

import com.example.demo.user.model.LogingUse;

public interface LogingUserDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Loging_User
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    List<LogingUse> selectByPrimaryAll(LogingUse user);
}
