package com.example.demo.user.dao;

import com.example.demo.user.model.LogingUse;

public interface LogingUseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Loging_User
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Loging_User
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    int insert(LogingUse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Loging_User
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    int insertSelective(LogingUse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Loging_User
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    LogingUse selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Loging_User
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    int updateByPrimaryKeySelective(LogingUse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Loging_User
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    int updateByPrimaryKey(LogingUse record);
}