package com.example.demo.user.model;

import java.util.Date;

public class Authority {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_Service.id
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_Service._key
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    private String key;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_Service._value
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    private String value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_Service.show_name
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    private String showName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_Service.create_time
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_Service.up_time
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    private Date upTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_Service._state
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_Service.Spare1
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    private String spare1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_Service.Spare2
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    private String spare2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_Service.Spare3
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    private String spare3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_Service.id
     *
     * @return the value of T_Service.id
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_Service.id
     *
     * @param id the value for T_Service.id
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_Service._key
     *
     * @return the value of T_Service._key
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public String getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_Service._key
     *
     * @param key the value for T_Service._key
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public void setKey(String key) {
        this.key = key == null ? null : key.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_Service._value
     *
     * @return the value of T_Service._value
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_Service._value
     *
     * @param value the value for T_Service._value
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_Service.show_name
     *
     * @return the value of T_Service.show_name
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public String getShowName() {
        return showName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_Service.show_name
     *
     * @param showName the value for T_Service.show_name
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public void setShowName(String showName) {
        this.showName = showName == null ? null : showName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_Service.create_time
     *
     * @return the value of T_Service.create_time
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_Service.create_time
     *
     * @param createTime the value for T_Service.create_time
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_Service.up_time
     *
     * @return the value of T_Service.up_time
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public Date getUpTime() {
        return upTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_Service.up_time
     *
     * @param upTime the value for T_Service.up_time
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public void setUpTime(Date upTime) {
        this.upTime = upTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_Service._state
     *
     * @return the value of T_Service._state
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_Service._state
     *
     * @param state the value for T_Service._state
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_Service.Spare1
     *
     * @return the value of T_Service.Spare1
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public String getSpare1() {
        return spare1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_Service.Spare1
     *
     * @param spare1 the value for T_Service.Spare1
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public void setSpare1(String spare1) {
        this.spare1 = spare1 == null ? null : spare1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_Service.Spare2
     *
     * @return the value of T_Service.Spare2
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public String getSpare2() {
        return spare2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_Service.Spare2
     *
     * @param spare2 the value for T_Service.Spare2
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public void setSpare2(String spare2) {
        this.spare2 = spare2 == null ? null : spare2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_Service.Spare3
     *
     * @return the value of T_Service.Spare3
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public String getSpare3() {
        return spare3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_Service.Spare3
     *
     * @param spare3 the value for T_Service.Spare3
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public void setSpare3(String spare3) {
        this.spare3 = spare3 == null ? null : spare3.trim();
    }
}