package com.example.demo.user.model;

import java.util.Date;

public class GroupData {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column G_Group.id
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column G_Group._key
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    private String key;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column G_Group._value
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    private String value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column G_Group.show_name
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    private String showName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column G_Group.id_up
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    private String idUp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column G_Group.key_up
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    private String keyUp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column G_Group.type_code
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    private String typeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column G_Group.type_name
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    private String typeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column G_Group.create_time
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column G_Group.up_time
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    private Date upTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column G_Group._state
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column G_Group.Spare1
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    private String spare1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column G_Group.Spare2
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    private String spare2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column G_Group.Spare3
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    private String spare3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column G_Group.id
     *
     * @return the value of G_Group.id
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column G_Group.id
     *
     * @param id the value for G_Group.id
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column G_Group._key
     *
     * @return the value of G_Group._key
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public String getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column G_Group._key
     *
     * @param key the value for G_Group._key
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public void setKey(String key) {
        this.key = key == null ? null : key.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column G_Group._value
     *
     * @return the value of G_Group._value
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column G_Group._value
     *
     * @param value the value for G_Group._value
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column G_Group.show_name
     *
     * @return the value of G_Group.show_name
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public String getShowName() {
        return showName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column G_Group.show_name
     *
     * @param showName the value for G_Group.show_name
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public void setShowName(String showName) {
        this.showName = showName == null ? null : showName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column G_Group.id_up
     *
     * @return the value of G_Group.id_up
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public String getIdUp() {
        return idUp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column G_Group.id_up
     *
     * @param idUp the value for G_Group.id_up
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public void setIdUp(String idUp) {
        this.idUp = idUp == null ? null : idUp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column G_Group.key_up
     *
     * @return the value of G_Group.key_up
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public String getKeyUp() {
        return keyUp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column G_Group.key_up
     *
     * @param keyUp the value for G_Group.key_up
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public void setKeyUp(String keyUp) {
        this.keyUp = keyUp == null ? null : keyUp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column G_Group.type_code
     *
     * @return the value of G_Group.type_code
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public String getTypeCode() {
        return typeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column G_Group.type_code
     *
     * @param typeCode the value for G_Group.type_code
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public void setTypeCode(String typeCode) {
        this.typeCode = typeCode == null ? null : typeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column G_Group.type_name
     *
     * @return the value of G_Group.type_name
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column G_Group.type_name
     *
     * @param typeName the value for G_Group.type_name
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName == null ? null : typeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column G_Group.create_time
     *
     * @return the value of G_Group.create_time
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column G_Group.create_time
     *
     * @param createTime the value for G_Group.create_time
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column G_Group.up_time
     *
     * @return the value of G_Group.up_time
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public Date getUpTime() {
        return upTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column G_Group.up_time
     *
     * @param upTime the value for G_Group.up_time
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public void setUpTime(Date upTime) {
        this.upTime = upTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column G_Group._state
     *
     * @return the value of G_Group._state
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column G_Group._state
     *
     * @param state the value for G_Group._state
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column G_Group.Spare1
     *
     * @return the value of G_Group.Spare1
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public String getSpare1() {
        return spare1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column G_Group.Spare1
     *
     * @param spare1 the value for G_Group.Spare1
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public void setSpare1(String spare1) {
        this.spare1 = spare1 == null ? null : spare1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column G_Group.Spare2
     *
     * @return the value of G_Group.Spare2
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public String getSpare2() {
        return spare2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column G_Group.Spare2
     *
     * @param spare2 the value for G_Group.Spare2
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public void setSpare2(String spare2) {
        this.spare2 = spare2 == null ? null : spare2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column G_Group.Spare3
     *
     * @return the value of G_Group.Spare3
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public String getSpare3() {
        return spare3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column G_Group.Spare3
     *
     * @param spare3 the value for G_Group.Spare3
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public void setSpare3(String spare3) {
        this.spare3 = spare3 == null ? null : spare3.trim();
    }
}