package com.example.demo.user.model;

import java.util.Date;

public class LogingUse {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_Loging_User.id
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_Loging_User.show_name
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    private String showName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_Loging_User.loging_name
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    private String logingName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_Loging_User.loging_password
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    private String logingPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_Loging_User.create_time
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_Loging_User.up_time
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    private Date upTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_Loging_User._state
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_Loging_User.Spare1
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    private String spare1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_Loging_User.Spare2
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    private String spare2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_Loging_User.Spare3
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    private String spare3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_Loging_User.id
     *
     * @return the value of T_Loging_User.id
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_Loging_User.id
     *
     * @param id the value for T_Loging_User.id
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_Loging_User.show_name
     *
     * @return the value of T_Loging_User.show_name
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public String getShowName() {
        return showName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_Loging_User.show_name
     *
     * @param showName the value for T_Loging_User.show_name
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public void setShowName(String showName) {
        this.showName = showName == null ? null : showName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_Loging_User.loging_name
     *
     * @return the value of T_Loging_User.loging_name
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public String getLogingName() {
        return logingName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_Loging_User.loging_name
     *
     * @param logingName the value for T_Loging_User.loging_name
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public void setLogingName(String logingName) {
        this.logingName = logingName == null ? null : logingName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_Loging_User.loging_password
     *
     * @return the value of T_Loging_User.loging_password
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public String getLogingPassword() {
        return logingPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_Loging_User.loging_password
     *
     * @param logingPassword the value for T_Loging_User.loging_password
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public void setLogingPassword(String logingPassword) {
        this.logingPassword = logingPassword == null ? null : logingPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_Loging_User.create_time
     *
     * @return the value of T_Loging_User.create_time
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_Loging_User.create_time
     *
     * @param createTime the value for T_Loging_User.create_time
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_Loging_User.up_time
     *
     * @return the value of T_Loging_User.up_time
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public Date getUpTime() {
        return upTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_Loging_User.up_time
     *
     * @param upTime the value for T_Loging_User.up_time
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public void setUpTime(Date upTime) {
        this.upTime = upTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_Loging_User._state
     *
     * @return the value of T_Loging_User._state
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_Loging_User._state
     *
     * @param state the value for T_Loging_User._state
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_Loging_User.Spare1
     *
     * @return the value of T_Loging_User.Spare1
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public String getSpare1() {
        return spare1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_Loging_User.Spare1
     *
     * @param spare1 the value for T_Loging_User.Spare1
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public void setSpare1(String spare1) {
        this.spare1 = spare1 == null ? null : spare1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_Loging_User.Spare2
     *
     * @return the value of T_Loging_User.Spare2
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public String getSpare2() {
        return spare2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_Loging_User.Spare2
     *
     * @param spare2 the value for T_Loging_User.Spare2
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public void setSpare2(String spare2) {
        this.spare2 = spare2 == null ? null : spare2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_Loging_User.Spare3
     *
     * @return the value of T_Loging_User.Spare3
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public String getSpare3() {
        return spare3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_Loging_User.Spare3
     *
     * @param spare3 the value for T_Loging_User.Spare3
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public void setSpare3(String spare3) {
        this.spare3 = spare3 == null ? null : spare3.trim();
    }

	@Override
	public String toString() {
		return "LogingUse [id=" + id + ", showName=" + showName + ", logingName=" + logingName + ", logingPassword="
				+ logingPassword + ", createTime=" + createTime + ", upTime=" + upTime + ", state=" + state
				+ ", spare1=" + spare1 + ", spare2=" + spare2 + ", spare3=" + spare3 + "]";
	}
    
}