package com.example.demo.user.model;

import java.util.Date;

public class MAPData {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_MAP.id
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_MAP.idone
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    private String idone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_MAP.idtwo
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    private String idtwo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_MAP.type_code
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    private String typeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_MAP.type_name
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    private String typeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_MAP.show_name
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    private String showName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_MAP.create_time
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_MAP.up_time
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    private Date upTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_MAP._state
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_MAP.Spare1
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    private String spare1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_MAP.Spare2
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    private String spare2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_MAP.Spare3
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    private String spare3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_MAP.id
     *
     * @return the value of M_MAP.id
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_MAP.id
     *
     * @param id the value for M_MAP.id
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_MAP.idone
     *
     * @return the value of M_MAP.idone
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public String getIdone() {
        return idone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_MAP.idone
     *
     * @param idone the value for M_MAP.idone
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public void setIdone(String idone) {
        this.idone = idone == null ? null : idone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_MAP.idtwo
     *
     * @return the value of M_MAP.idtwo
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public String getIdtwo() {
        return idtwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_MAP.idtwo
     *
     * @param idtwo the value for M_MAP.idtwo
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public void setIdtwo(String idtwo) {
        this.idtwo = idtwo == null ? null : idtwo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_MAP.type_code
     *
     * @return the value of M_MAP.type_code
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public String getTypeCode() {
        return typeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_MAP.type_code
     *
     * @param typeCode the value for M_MAP.type_code
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public void setTypeCode(String typeCode) {
        this.typeCode = typeCode == null ? null : typeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_MAP.type_name
     *
     * @return the value of M_MAP.type_name
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_MAP.type_name
     *
     * @param typeName the value for M_MAP.type_name
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName == null ? null : typeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_MAP.show_name
     *
     * @return the value of M_MAP.show_name
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public String getShowName() {
        return showName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_MAP.show_name
     *
     * @param showName the value for M_MAP.show_name
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public void setShowName(String showName) {
        this.showName = showName == null ? null : showName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_MAP.create_time
     *
     * @return the value of M_MAP.create_time
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_MAP.create_time
     *
     * @param createTime the value for M_MAP.create_time
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_MAP.up_time
     *
     * @return the value of M_MAP.up_time
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public Date getUpTime() {
        return upTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_MAP.up_time
     *
     * @param upTime the value for M_MAP.up_time
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public void setUpTime(Date upTime) {
        this.upTime = upTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_MAP._state
     *
     * @return the value of M_MAP._state
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_MAP._state
     *
     * @param state the value for M_MAP._state
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_MAP.Spare1
     *
     * @return the value of M_MAP.Spare1
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public String getSpare1() {
        return spare1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_MAP.Spare1
     *
     * @param spare1 the value for M_MAP.Spare1
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public void setSpare1(String spare1) {
        this.spare1 = spare1 == null ? null : spare1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_MAP.Spare2
     *
     * @return the value of M_MAP.Spare2
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public String getSpare2() {
        return spare2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_MAP.Spare2
     *
     * @param spare2 the value for M_MAP.Spare2
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public void setSpare2(String spare2) {
        this.spare2 = spare2 == null ? null : spare2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_MAP.Spare3
     *
     * @return the value of M_MAP.Spare3
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public String getSpare3() {
        return spare3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_MAP.Spare3
     *
     * @param spare3 the value for M_MAP.Spare3
     *
     * @mbg.generated Tue Jun 05 11:10:00 CST 2018
     */
    public void setSpare3(String spare3) {
        this.spare3 = spare3 == null ? null : spare3.trim();
    }
}